services:
  postgres:
    image: helenaish/nodejs2024q3-service-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    networks:
      - my_custom_network

  app:
    image: helenaish/nodejs2024q3-service-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_DATABASE}
    depends_on:
      - postgres
    networks:
      - my_custom_network
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - /app/node_modules
      - ./logs:/app/dist/logs
volumes:
  db-data:
  db-logs:

networks:
  my_custom_network:
    driver: bridge